version: '3.7'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./config/db.env
    environment:
      - MYSQL_ROOT_PASSWORD=Password1234?
    networks:
      - db

  app:
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8484:80
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - ./config/db.env
    environment:
      - MYSQL_HOST=db
    restart: always
    networks:
      - default
      - db
    depends_on:
      - db

volumes:
  db:
  nextcloud:

networks:
  db:
